export const ACTION_CHANGE_TITLEHEADER = 'ACTION_CHANGE_TITLEHEADER'
export const ACTION_CHANGE_SUBTITLEHEADER = 'ACTION_CHANGE_SUBTITLEHEADER'
export const ACTION_CHANGE_TEXTBUTTONNEW = 'ACTION_CHANGE_TEXTBUTTONNEW'

export const ACTION_CHANGE_PAGES = 'ACTION_CHANGE_PAGES'
export const ACTION_CHANGE_LIMIT = 'ACTION_CHANGE_LIMIT'
export const ACTION_CHANGE_TOTALRESULT = 'ACTION_CHANGE_TOTALRESULT'

export const ACTION_CHANGE_LISTTAGS = 'ACTION_CHANGE_LISTTAGS'
export const ACTION_CHANGE_TAGSELECTED = 'ACTION_CHANGE_TAGSELECTED'
export const ACTION_CHANGE_TAG_FILTERNAME = 'ACTION_CHANGE_TAG_FILTERNAME'

export const ACTION_CHANGE_LISTEXPERTS = 'ACTION_CHANGE_LISTEXPERTS'
export const ACTION_CHANGE_EXPERTSELECTED = 'ACTION_CHANGE_EXPERTSELECTED'
export const ACTION_CHANGE_EXPERT_FILTERNAME = 'ACTION_CHANGE_EXPERT_FILTERNAME'
export const ACTION_CHANGE_EXPERT_FILTERSTATE = 'ACTION_CHANGE_EXPERT_FILTERSTATE'
export const ACTION_CHANGE_EXPERT_FILTERTAG = 'ACTION_CHANGE_EXPERT_FILTERTAG'
export const ACTION_CHANGE_EXPERT_FILTERSCORE = 'ACTION_CHANGE_EXPERT_FILTERSCORE'
