export const ACTION_CHANGE_TITLEHEADER = 'ACTION_CHANGE_TITLEHEADER'
export const ACTION_CHANGE_SUBTITLEHEADER = 'ACTION_CHANGE_SUBTITLEHEADER'
export const ACTION_CHANGE_TEXTBUTTONNEW = 'ACTION_CHANGE_TEXTBUTTONNEW'
export const ACTION_CHANGE_PAGES = 'ACTION_CHANGE_PAGES'
export const ACTION_CHANGE_LIMIT = 'ACTION_CHANGE_LIMIT'
export const ACTION_CHANGE_TOTALRESULT = 'ACTION_CHANGE_TOTALRESULT'


